steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/assinatura-pdf', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/assinatura-pdf']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'assinatura-pdf', '--image', 'gcr.io/$PROJECT_ID/assinatura-pdf', '--platform', 'managed', '--region', 'southamerica-east1', '--allow-unauthenticated']
